name: proyek2
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  provider: ^6.1.4
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  path: ^1.9.1
  intl: ^0.20.2
  file_picker: ^9.2.3
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.3.0
  iconsax: ^0.0.8
  flutter:
    sdk: flutter
  get:

  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  permission_handler: ^11.0.1
  logger: ^2.5.0
  mime: ^2.0.0
  http_parser: ^4.1.2
  dio: ^5.8.0+1
  flutter_downloader: ^1.12.0
  flutter_local_notifications: ^19.2.1
  open_file: ^3.5.10

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo-kabupaten-indramayu.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
