// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKypCmRH-6ISdabNu1mQLmlFMI9zsPs4o',
    appId: '1:71145975091:web:c1b561695ce37673ba2246',
    messagingSenderId: '71145975091',
    projectId: 'crud-tubes-pab',
    authDomain: 'crud-tubes-pab.firebaseapp.com',
    storageBucket: 'crud-tubes-pab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfCMaOKfybYwW1maXfnJ6dzZUn-FPz53E',
    appId: '1:71145975091:android:3d5ca5f1d34991caba2246',
    messagingSenderId: '71145975091',
    projectId: 'crud-tubes-pab',
    storageBucket: 'crud-tubes-pab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdV0Qt6F2W-D0yr_ZZ9cxWqbbcLTopJNk',
    appId: '1:71145975091:ios:b3b58db5ac7aa5adba2246',
    messagingSenderId: '71145975091',
    projectId: 'crud-tubes-pab',
    storageBucket: 'crud-tubes-pab.firebasestorage.app',
    iosBundleId: 'com.example.proyek2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdV0Qt6F2W-D0yr_ZZ9cxWqbbcLTopJNk',
    appId: '1:71145975091:ios:b3b58db5ac7aa5adba2246',
    messagingSenderId: '71145975091',
    projectId: 'crud-tubes-pab',
    storageBucket: 'crud-tubes-pab.firebasestorage.app',
    iosBundleId: 'com.example.proyek2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKypCmRH-6ISdabNu1mQLmlFMI9zsPs4o',
    appId: '1:71145975091:web:80c71a54cd42611dba2246',
    messagingSenderId: '71145975091',
    projectId: 'crud-tubes-pab',
    authDomain: 'crud-tubes-pab.firebaseapp.com',
    storageBucket: 'crud-tubes-pab.firebasestorage.app',
  );
}
